from __future__ import annotations

from dataclasses import replace
from math import ceil

from .models import (
    AdaptiveLoadProfile,
    AdaptiveV2LoadProfile,
    ContinuousLoadProfile,
    ExploreRefineLoadProfile,
    GoodputPlateauLoadProfile,
    LoadProfile,
    SpikeLoadProfile,
    StairsLoadProfile,
    SteadyLoadProfile,
)


LOAD_PROFILE_REGISTRY: dict[str, LoadProfile] = {
    # Aligned with current bench.sh defaults for predictable behavior.
    "default": SteadyLoadProfile(
        name="default", run_time_s=180, wait_min_s=1.0, wait_max_s=1.0, locust_processes=8, users=1000
    ),
    "quick-check": SteadyLoadProfile(
        name="quick-check", users=200, run_time_s=30, wait_min_s=1.0, wait_max_s=1.0, locust_processes=8
    ),

    "k8s-adaptive": AdaptiveLoadProfile(
        name="k8s-adaptive",
        sla_ms=300,
        start_users=50,
        max_users=100_000,
        min_step_users=25,
        max_step_users=500,
        spawn_rate=50,
        step_duration_s=30,
        trim_s=10,
        sample_every_s=5,
        settle_samples=3,
        quantile=0.95,
        run_time_s=180,        
        wait_min_s=1.0,
        wait_max_s=1.0,
        locust_processes=32,
    ),

    "k8s-adaptive-v2-new": AdaptiveV2LoadProfile(
        name="k8s-adaptive-v2-new",
        sla_ms=300,
        failure_threshold_pct=5.0,
        start_users=100,
        max_users=100_000,
        min_step_users=10,
        max_step_users=1000,
        spawn_rate=200,
        warmup_step_duration_s=30,
        min_step_duration_s=20,
        max_step_duration_s=40,
        # trim_s >= the 10s windowed-p95 lookback so the measurement window
        # never straddles the previous user level after a step change.
        trim_s=15,
        sample_every_s=1,
        min_settle_samples=5,
        quantile=0.95,
        stability_drift_threshold_pct=5.0,
        plateau_stop_steps=3,
        plateau_goodput_threshold_pct=5.0,
        run_time_s=420,
        wait_min_s=1.0,
        wait_max_s=1.0,
        locust_processes=32,
    ),

    "k8s-adaptive-v2-new-long": AdaptiveV2LoadProfile(
        name="k8s-adaptive-v2-new-long",
        sla_ms=300,
        failure_threshold_pct=5.0,
        start_users=100,
        max_users=100_000,
        min_step_users=10,
        max_step_users=1000,
        spawn_rate=200,
        warmup_step_duration_s=30,
        min_step_duration_s=20,
        max_step_duration_s=40,
        # trim_s >= the 10s windowed-p95 lookback so the measurement window
        # never straddles the previous user level after a step change.
        trim_s=15,
        sample_every_s=1,
        min_settle_samples=5,
        quantile=0.95,
        stability_drift_threshold_pct=5.0,
        plateau_stop_steps=5,
        plateau_goodput_threshold_pct=5.0,
        run_time_s=600,
        wait_min_s=1.0,
        wait_max_s=1.0,
        locust_processes=32,
    ),

    "k8s-adaptive-v2-new-long-10": AdaptiveV2LoadProfile(
        name="k8s-adaptive-v2-new-long-10",
        sla_ms=300,
        failure_threshold_pct=5.0,
        start_users=100,
        max_users=100_000,
        min_step_users=10,
        max_step_users=1000,
        spawn_rate=200,
        warmup_step_duration_s=30,
        min_step_duration_s=20,
        max_step_duration_s=40,
        # trim_s >= the 10s windowed-p95 lookback so the measurement window
        # never straddles the previous user level after a step change.
        trim_s=15,
        sample_every_s=1,
        min_settle_samples=10,
        quantile=0.95,
        stability_drift_threshold_pct=5.0,
        plateau_stop_steps=5,
        plateau_goodput_threshold_pct=5.0,
        run_time_s=600,
        wait_min_s=1.0,
        wait_max_s=1.0,
        locust_processes=32,
    ),

    "k8s-goodput-plateau": GoodputPlateauLoadProfile(
        name="k8s-goodput-plateau",
        failure_threshold_pct=2.0,
        collapse_threshold_pct=10.0,
        overload_p95_ms=1000.0,
        start_users=100,
        max_users=100_000,
        min_step_users=10,
        max_step_users=300,
        step_up_gain=1.5,
        efficiency_good_threshold=0.95,
        drain_time_s=30,
        spawn_rate=100,
        warmup_step_duration_s=20,
        min_step_duration_s=20,
        max_step_duration_s=40,
        trim_s=15,
        sample_every_s=1,
        min_settle_samples=10,
        quantile=0.95,
        stability_drift_threshold_pct=5.0,
        plateau_stop_steps=2,
        plateau_goodput_threshold_pct=5.0,
        overload_backoff_max=2,
        run_time_s=1800,
        wait_min_s=1.0,
        wait_max_s=1.0,
        locust_processes=32,
    ),

    "k8s-goodput-plateau-long": GoodputPlateauLoadProfile(
        name="k8s-goodput-plateau-long",
        failure_threshold_pct=2.0,
        collapse_threshold_pct=10.0,
        overload_p95_ms=1000.0,
        start_users=100,
        max_users=100_000,
        min_step_users=10,
        max_step_users=1000,
        step_up_gain=1.2,
        efficiency_good_threshold=0.95,
        drain_time_s=30,
        spawn_rate=200,
        warmup_step_duration_s=30,
        min_step_duration_s=20,
        max_step_duration_s=40,
        trim_s=15,
        sample_every_s=1,
        min_settle_samples=10,
        quantile=0.95,
        stability_drift_threshold_pct=5.0,
        plateau_stop_steps=2,
        plateau_goodput_threshold_pct=5.0,
        overload_backoff_max=2,
        run_time_s=600,
        wait_min_s=1.0,
        wait_max_s=1.0,
        locust_processes=32,
    ),

    "k8s-explore-refine": ExploreRefineLoadProfile(
        name="k8s-explore-refine",
        failure_threshold_pct=2.0,
        overload_p95_ms=1000.0,
        start_users=100,
        max_users=100_000,
        run_time_s=1800,
        sample_every_s=1,
        quantile=0.95,
        wait_min_s=1.0,
        wait_max_s=1.0,
        explore_warmup_duration_s=30,
        explore_ramp_user_fraction_per_s=0.04,
        explore_min_step_users=20,
        explore_goodput_stop_ratio=0.95,
        explore_stop_steps=3,
        recovery_floor_fraction=0.75,
        recovery_settle_duration_s=45,
        recovery_retry_drop_fraction=0.15,
        recovery_max_retries=3,
        refine_max_step_duration_s=60,
        refine_min_settle_samples=10,
        refine_trim_s=10,
        refine_min_step_users=10,
        refine_max_step_fraction=0.05,
        refine_goodput_stability_pct=5.0,
    ),

    # Load profiles for the BaxBench benchmark.
    "cont-20000": ContinuousLoadProfile(
        name="cont-20000",
        start_users=0,
        target_users=2000,
        spawn_rate=20,
        run_time_s=240,
        wait_min_s=0,
        wait_max_s=0,
        locust_processes=8,
    ),
    "stairs-100-100-30-15": StairsLoadProfile(
        name="stairs-100-100-30-15",
        start_users=100,
        step_users=100,
        step_duration_s=30,
        steps=15,
        run_time_s=450,
        wait_min_s=1.0,
        wait_max_s=1.0,
        locust_processes=32,
    ),
    "stairs-800-100-30-12": StairsLoadProfile(
        name="stairs-800-100-30-12",
        start_users=800,
        step_users=100,
        step_duration_s=30,
        steps=12,
        run_time_s=360,
        wait_min_s=1.0,
        wait_max_s=1.0,
        locust_processes=8,
    ),
    "stairs-1500-100-30-15": StairsLoadProfile(
        name="stairs-1500-100-30-15",
        start_users=1500,
        step_users=100,
        step_duration_s=30,
        steps=15,
        run_time_s=450,
        wait_min_s=1.0,
        wait_max_s=1.0,
        locust_processes=8,
    ),
    "stairs-500-100-30-10": StairsLoadProfile(
        name="stairs-500-100-30-10",
        start_users=500,
        step_users=100,
        step_duration_s=30,
        steps=10,
        run_time_s=300,
        wait_min_s=1.0,
        wait_max_s=1.0,
        locust_processes=8,
    ),
    "spike-500-1000-30-10": SpikeLoadProfile(
        name="spike-500-1000-30-10",
        base_users=500,
        spike_users=1000,
        interval_s=30,
        duration_s=10,
        run_time_s=300,
        wait_min_s=1.0,
        wait_max_s=1.0,
        locust_processes=8,
    ),
}


def resolve_load_profile(name: str | None) -> LoadProfile:
    key = (name or "default").strip()
    if key not in LOAD_PROFILE_REGISTRY:
        known = ", ".join(sorted(LOAD_PROFILE_REGISTRY))
        raise ValueError(f"Unknown load profile '{key}'. Known profiles: {known}")
    return LOAD_PROFILE_REGISTRY[key]
